language: java
jdk:
  - oraclejdk8
before_install:
  - cat ~/.m2/settings.xml # check before
  # https://github.com/travis-ci/travis-ci/issues/4629
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - cat ~/.m2/settings.xml # check after
install: true
script: mvn clean install
